version: "3"
services:
  app:
    image: ghcr.io/<username>/<image-name>:<tag>
    # if you want to build it yourself, replace `image` with `build`
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    ports:
      - 8080:80
