const MUTATIONS = {
  SET_VISIBLE_POSTS_DIALOG: "SET_VISIBLE_POSTS_DIALOG",
  ADD_VISIBLE_POSTS_DIALOG: "ADD_VISIBLE_POSTS_DIALOG",

  SET_AUTHENTICATION: "SET_AUTHENTICATION",
  SET_DETAILS_VIEW: "SET_DETAILS_VIEW",
};
const GETTERS = {
  IS_LOGGED_IN: "IS_LOGGED_IN",
  GET_DETAILS_VIEW_POST: "GET_DETAILS_VIEW_POST",
  GET_VISIBLE_POSTS: "GET_VISIBLE_POSTS", // main list
  GET_VISIBLE_POSTS_DIALOG: "GET_VISIBLE_POSTS_DIALOG", // list in dialog
  GET_NOT_YET_LOADED_POSTS_DIALOG: "GET_NOT_YET_LOADED_POSTS_DIALOG", // list in dialog
  GET_FULLSCREEN_POST: "GET_FULLSCREEN_POST",
  GET_FULLSCREEN_POST_ID: "GET_FULLSCREEN_POST_ID",
  GET_POST: "GET_POST",
  GET_TAGS: "GET_TAGS",
  GET_CURRENT_PAGE_NUMBER: "GET_CURRENT_PAGE_NUMBER",
  GET_MAX_PAGE_NUMBER: "GET_MAX_PAGE_NUMBER",
  GET_CURRENT_PAGE_LOADED: "GET_CURRENT_PAGE_LOADED",
  GET_VISIBLE_POSTS_BLACKLISTED: "GET_VISIBLE_POSTS_BLACKLISTED",

  // other settings
  POST_BUTTONS_LAYOUT: "POST_BUTTONS_LAYOUT",

  // string settings
  POST_COMPACTNESS: "POST_COMPACTNESS",
  POST_LAYOUT: "POST_LAYOUT",
  NAVIGATION_TYPE: "NAVIGATION_TYPE",
  FULLSCREEN_BUTTONS_LAYOUT: "FULLSCREEN_BUTTONS_LAYOUT",
  FULLSCREEN_PREVIOUS_NEXT_LAYOUT: "FULLSCREEN_PREVIOUS_NEXT_LAYOUT",
  MASCOT_STYLE: "MASCOT_STYLE",

  // boolean settings
  IS_LOW_RESOLUTION_MODE: "IS_LOW_RESOLUTION_MODE",
  IS_SUGGESTION_ORDERED: "IS_SUGGESTION_ORDERED",
  IS_AUTO_LOAD: "IS_AUTO_LOAD",
  IS_BOTTOM_LOAD: "IS_BOTTOM_LOAD",
  IS_BACKGROUND_COLORED: "IS_BACKGROUND_COLORED",
  IS_COMPACT_MODE: "IS_COMPACT_MODE",
  IS_FAST_LOAD_MODE: "IS_FAST_LOAD_MODE",
  IS_DESCRIPTIVE_FILENAME: "IS_DESCRIPTIVE_FILENAME",
  IS_PAGINATED_MODE: "IS_PAGINATED_MODE",
  IS_DOWNLOAD_PROGRESS: "IS_DOWNLOAD_PROGRESS",
  IS_CONCURRENT_DOWNLOADS: "IS_CONCURRENT_DOWNLOADS",
  IS_TAGLINE_DISPLAYED: "IS_TAGLINE_DISPLAYED",

  // numerical settings
  POST_FETCH_COUNT: "POST_FETCH_COUNT",
  TAG_FETCH_COUNT: "TAG_FETCH_COUNT",
  SUGGESTION_COUNT: "SUGGESTION_COUNT",
};
const ACTIONS = {
  SET_VISIBLE_POSTS_DIALOG: "SET_VISIBLE_POSTS_DIALOG",
  ADD_VISIBLE_POSTS_DIALOG: "ADD_VISIBLE_POSTS_DIALOG",

  SET_DETAILS_VIEW: "SET_DETAILS_VIEW",

  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",

  SET_FULLSCREEN_POST_ID: "SET_FULLSCREEN_POST_ID",

  SET_CURRENT_PAGE_NUMBER: "SET_CURRENT_PAGE_NUMBER",
  SET_MAX_PAGE_NUMBER: "SET_MAX_PAGE_NUMBER",
};
export { MUTATIONS, GETTERS, ACTIONS };
