const GETTERS = {
  IS_LOGGED_IN: "IS_LOGGED_IN",

  // string settings
  POST_COMPACTNESS: "POST_COMPACTNESS",
  POST_LAYOUT: "POST_LAYOUT",
  MASCOT_STYLE: "MASCOT_STYLE",

  // boolean settings
  IS_LOW_RESOLUTION_MODE: "IS_LOW_RESOLUTION_MODE",
  IS_COMPACT_MODE: "IS_COMPACT_MODE",
  IS_FAST_LOAD_MODE: "IS_FAST_LOAD_MODE",
  IS_DESCRIPTIVE_FILENAME: "IS_DESCRIPTIVE_FILENAME",

  // numerical settings
  POST_FETCH_COUNT: "POST_FETCH_COUNT",
  TAG_FETCH_COUNT: "TAG_FETCH_COUNT",
  SUGGESTION_COUNT: "SUGGESTION_COUNT",
};

const ACTIONS = {
  LOG_IN: "LOG_IN",
  LOG_OUT: "LOG_OUT",
};

export { GETTERS, ACTIONS };
